### ISSUE TITLE
Time losses

### ISSUE THREAD

**Issue by AlexBrunetti** [jonathanmcdermid/Hopper-Chess-Engine#2]
Hi,

in my tests at 1'+1" the new version loses around 20% of games on time. I suggest to improve time management.

Alex

**Comment by jonathanmcdermid** [comment]
I've added some basic time management functionalities and I don't think it should be getting flagged any more. Let me know if it works!

**Comment by AlexBrunetti** [comment]
Good, you can find there the results of my tests of new engine versions, Hopper's too.

**Comment by jonathanmcdermid** [comment]
Thanks a lot!
